language: csharp
solution: HtmlBuilders.sln
install:
  - nuget restore HtmlBuilders.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release HtmlBuilders.sln
  - xbuild /p:Configuration=Release ./HtmlBuilders.Tests/HtmlBuilders.Tests.csproj
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./HtmlBuilders.Tests/bin/Release/HtmlBuilders.Tests.dll